language: cpp
sudo: false
os:
 - linux
notifications:
  email:
#    recipients:
#      - one@example.com
#      - other@example.com
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - g++-4.9
    - g++-5
    - clang-3.7

before_install:
 - git submodule update --init --recursive

script:
 - cd test
 - ./withgcc.sh
 - g++-5 -std=c++14 -o atuple -O3 atuple.cpp
 - ./atuple
 - g++-5 -std=c++14 -o ringbuffer_log -O3 ringbuffer_log.cpp
 - ./ringbuffer_log
 - g++-5 -std=c++14 -o spinlock_tribool -O3 spinlock_tribool.cpp
 - ./spinlock_tribool
 
after_success:
# - bash -x ./update_coveralls.sh `pwd`

after_failure:
