# version format
version: 0.01.{build}-{branch}
 
# branches to build
branches:
  # blacklist
  except:
    - gh-pages
skip_tags: true
 
# Operating system (build VM template)
os: Visual Studio 2017
init:
  - git config --global core.longpaths true

clone_folder: c:\quickcpplib
platform: x64 
configuration: Release

before_build:
  - git checkout master
  - git submodule update --init --recursive
build_script:
  - ctest -S .ci.cmake -V --build-generator "Visual Studio 15 2017 Win64"
after_build:

before_test:
test_script:
after_test:

on_success:
on_failure:
on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path cmake_ci\merged_junit_results.xml))
