name: CI

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  Linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        compiler: [clang++, g++]
    env:
      NAME: Linux-${{ matrix.compiler }}
      CXX: ${{ matrix.compiler }}
          
    steps:
    - uses: actions/checkout@v2

    - name: cmake tests linux
      shell: bash
      run: ctest -S .ci.cmake -V

  MacOS:
    runs-on: macos-10.15
    env:
      NAME: MacOS
          
    steps:
    - uses: actions/checkout@v2

    - name: cmake tests osx
      shell: bash
      run: ctest -S .ci.cmake -V -E noexcept

  WinVS2019:
    runs-on: windows-2019
    env:
      NAME: WinVS2019
          
    steps:
    - uses: actions/checkout@v2

    - name: cmake tests windows
      shell: bash
      run: ctest -S .ci.cmake -V
