name: CMake

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]
        compiler: [clang++, g++, msvc]
        exclude:
          - os: macos-10.15
            compiler: g++
          - os: macos-10.15
            compiler: msvc
          - os: windows-2019
            compiler: clang++
          - os: windows-2019
            compiler: g++
          
    steps:
    - uses: actions/checkout@v2

    - name: cmake tests osx
      if: ${{ matrix.os == 'macos-10.15' }}
      shell: bash
      run: ctest -S .ci.cmake -V -E noexcept

    - name: cmake tests linux
      if: ${{ matrix.os == 'ubuntu-18.04' }}
      env:
        CXX: ${{ matrix.compiler }}
      shell: bash
      run: ctest -S .ci.cmake -V

    - name: cmake tests windows
      if: ${{ matrix.os == 'windows-2019' }}
      shell: bash
      run: ctest -S .ci.cmake -V
